env:
  global:
  - GIT_NAME: "'travis autodeploy'"
  - GIT_EMAIL: autodeploy@travis-ci.org
  - GH_REF: git@github.com:micnigh/resume.git

sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose up --force-recreate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: .tmp/production/dist/
  on:
    branch: master
