env:
  global:
  - GIT_NAME: "'travis autodeploy'"
  - GIT_EMAIL: autodeploy@travis-ci.org
  - GH_REF: git@github.com:micnigh/resume.git

sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - npm install -g gulp typings bower

install:
  - npm install

script:
  - gulp --gulpfile gulpfile.transpile.js build
  - docker-compose build
  - docker-compose up --force-recreate
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
